/*
    This file was auto-generated by genioc tool

    ----

    Do NOT manually edit it!

    ----

    To update this file with newer dependencies - run:

    $ genioc

    or 

    $ genioc --watch

    to continuously watch after files
*/

import { AbstractContainer, DefaultDependencyToken } from "../src";

export type GeneratedDependencyToken = "CircularB" | "CircularA" | "IConfig" | "IUserRepository" | "IMailer" | "ILogger" | DefaultDependencyToken;

const Container = new AbstractContainer<GeneratedDependencyToken>(
  {
  "CircularA": [
    "CircularB"
  ],
  "CircularB": [
    "CircularA"
  ],
  "AbstractContainer": [],
  "UserRepository": [],
  "ConsoleLogger": [],
  "ConsoleMailer": [
    "IConfig"
  ],
  "UserService": [
    "IUserRepository",
    "IMailer",
    "ILogger"
  ]
}
);

export default Container;
