/*
    This file was auto-generated by genioc tool

    ----

    Do NOT manually edit it!

    ----

    To update this file with newer dependencies - run:

    $ genioc

    or 

    $ genioc --watch

    to continuously watch after files
*/

import { AbstractContainer, DefaultDependencyToken } from "../src";

export type GeneratedDependencyToken = "IUserRepository" | "IMailer" | DefaultDependencyToken;

const Container = new AbstractContainer<GeneratedDependencyToken>(
  {
  "AbstractContainer": [],
  "UserRepository": [],
  "ConsoleMailer": [],
  "UserService": [
    "IUserRepository",
    "IMailer"
  ]
}
);

export default Container;
