import { UserRepository } from "./user.repository";
import { UserService } from "./user.service";

import container from "./genioc.autogenerated";
import { ConsoleMailer } from "./mailer";
import { ConsoleLogger } from "./logger";
import { IConfig } from "./config";

function bindStuff() {
  container.bind("IUserRepository", UserRepository);
  container.bindSelf(UserService);
  container.bind('IMailer', ConsoleMailer);
  container.bind('ILogger', ConsoleLogger);
  container.bindValue<IConfig>('IConfig', {
    environment: 'production'
  });
}

function doUsefulWork() {
  const userService = container.get<UserService>(UserService);

  userService.register("John Doe", "john@doe.com");
}

async function run() {
  bindStuff();

  doUsefulWork();
}

run();
