import { UserRepository } from "./user.repository";
import { UserService } from "./user.service";

// import container from "./genioc.autogenerated";

function bindStuff() {
  // container.bind("IUserRepository", UserRepository);
  // container.bindSelf(UserService);
}

function doUsefulWork() {
  // const userService = container.get<UserService>(UserService);
// 
  // userService.register("John Doe", "john@doe.com");
}

async function run() {
  bindStuff();

  doUsefulWork();
}

run();
